---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
    web_root_path: /var/www
    reason_package_path: /var/reason_package
    php_xdebug_remote_host: localhost
    php_xdebug_remote_port: "9000"
  user: vagrant
  become: yes

  tasks:
  - name: ensure apache & php are installed
    apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
    with_items:
      - apache2
      - php5
      - libapache2-mod-php5
      - php5-mysql
      - php5-tidy
      - php5-curl
      - imagemagick
      - php5-xdebug
    notify:
    - restart apache

  - name: ensure apache is running
    service: name=apache2 state=started

  - name: move XDebug INI file into place
    template: >
      src={{ item.src }}
      dest={{ item.dest }} owner=root group=root mode=0644
    with_items:
      - { src: 20-xdebug.ini.j2, dest: /etc/php5/apache2/conf.d/20-xdebug.ini }
    notify:
      - restart apache

  - name: ensure MySQL is installed
    apt: pkg={{ item }} state=present
    with_items:
      - mysql-server
      - python-mysqldb

  - name: Start the MySQL service
    service: name=mysql state=started

  - name: create reason databases
    mysql_db: db={{ item }} state=present
    with_items:
      - reason
    notify:
      - import reason databases
      - open setup in browser

  # WARNING!: usernames and passwords should not be specified here for production!
  - name: create user reason_user...NO PRODUCTION PASSWORDS
    mysql_user: state=present name=reason_user password=some_password priv=reason.*:ALL

  - name: create reason symlinks
    file: src={{ item.src }} dest={{ item.dest }} owner=www-data group=www-data state=link
    with_items:
      - { src: '{{ reason_package_path }}/reason_4.0/www/', dest: '{{ web_root_path }}/reason' }
      - { src: '{{ reason_package_path }}/www/', dest: '{{ web_root_path }}/reason_package' }
      - { src: '{{ reason_package_path }}/thor/', dest: '{{ web_root_path }}/thor' }
      - { src: '{{ reason_package_path }}/loki_2.0/', dest: '{{ web_root_path }}/loki_2.0' }
      - { src: '{{ reason_package_path }}/flvplayer/', dest: '{{ web_root_path }}/flvplayer' }
      - { src: '{{ reason_package_path }}/jquery/', dest: '{{ web_root_path }}/jquery' }
      - { src: '{{ reason_package_path }}/date_picker/', dest: '{{ web_root_path }}/date_picker' }

  - name: set permissions on write required dirs
    file: path={{ item }} group=www-data mode=0774 state=directory recurse=yes
    with_items:
      - '{{ web_root_path }}/'
      - '{{ reason_package_path }}/reason_4.0/data/'

  - name: copy php.ini to /etc/php5/apache2/php.ini
    copy: src=php.ini dest=/etc/php5/apache2/php.ini owner=root group=root mode=0644
    notify:
    - restart apache

  - name: Assures /vagrant/settings dir exists
    file: path=/vagrant/settings state=directory

  - name: copy reason config files for vagrant
    copy: src={{ item }} dest=/vagrant/settings/{{ item }}
    with_items:
      - dbs.xml
      - error_handler_settings.php

  - name: copy apache config with rewrite FileInfo
    copy: src=default dest=/etc/apache2/sites-available/000-default.conf owner=root group=root mode=0644
    notify:
    - restart apache

  - name: Apache enable rewrite
    command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
    notify:
    - restart apache

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: import reason databases
      mysql_db: db={{ item.db }} target={{ item.target }} state=import
      with_items:
        - { db: reason, target: /var/reason_package/reason_4.0/data/dbs/reason4.8.sql }

    - name: open setup in browser
      become: no
      local_action: shell open http://192.168.56.101/reason/setup.php

